# Exported from Render on 2026-05-03T14:13:54Z
version: "1"
projects:
- name: My project
  environments:
  - name: Production
    services:
    - type: web
      name: HEALTH-PASSPORT-BLOCKCHAIN-MEETS-AI-FOR-WELLNESS-
      runtime: docker
      repo: https://github.com/Venkatesh123-start/HEALTH-PASSPORT-BLOCKCHAIN-MEETS-AI-FOR-WELLNESS-
      plan: free
      region: oregon
      dockerContext: .
      dockerfilePath: ./Dockerfile
      autoDeployTrigger: commit
